### ISSUE TITLE
[Bug]: Square Brackets Are Removed From Usernames

### ISSUE THREAD

**Issue by thecoolreaver** [FurryCoders/FALocalRepo#11]
### Version

4.4.6

### What happened?

attempting to download user "[l[i]s](https://www.furaffinity.net/user/l[i]s/)" becomes "[lis](https://www.furaffinity.net/user/lis/)" and does not download the proper user data

### How to reproduce the bug?

`falocalrepo download users -u l[i]s -f gallery -f scraps -f favorites -f journals -f userpage`

### Relevant log output

```shell
falocalrepo download users -u l[i]s -f gallery -f scraps -f favorites -f journals -f userpage
Downloading: lis/gallery
Downloading: lis/scraps
Downloading: lis/favorites
Downloading: lis/journals
Downloading: lis/userpage
lis
```

**Comment by MatteoCampinoti94** [comment]
My bad, I thought square brackets weren't allowed in usernames so the program removes them.

I'll fix it with a patch in a few minutes :)

**Comment by MatteoCampinoti94** [comment]
Okay, make that 3 hours x3

Took the chance to patch FAAPI, the database, and the server dependencies as well, and fixed some security vulnerabilities :)

A new version will be online momentarily, just needs to build.

**Comment by MatteoCampinoti94** [comment]
Version [4.4.7](https://github.com/FurryCoders/FALocalRepo/releases/tag/v4.4.7) is out :)
